### ISSUE TITLE
How did you get values for the plotMap.m?

### ISSUE THREAD

**Issue by vinhk** [gustavoavellar/multi-uav-planning#2]
I wanted to know how did you get these values from the 

> hangar.jpg 

base = [897.5000  491.5000];
N = -20.72613271;
W = -43.81682358;
S = -20.74471033;
E = -43.77901375;`

**Comment by gustavoavellar** [comment]
This image is a print screen form google maps website. To get N, W, S and E coordinates I pick two easily identifiable spots, usually, next in the corners of the image (NW and SE corners) and use google maps to check for the coordinates for these spots. The values for the base are its coordinates in pixels (image workspace).

**Comment by vinhk** [comment]
Thank you @gustavoavellar
