### ISSUE TITLE
How did you use the png map file to do overlay on Google Map?

### ISSUE THREAD

**Issue by vinhk** [gustavoavellar/multi-uav-planning#3]
Hi,

I am having difficulty trying to understand how you overlay you png file on Google Map. What did you use to obtain the values for the coordinates? As you know the map was in meters to be able to use UAV footprint.

**Comment by gustavoavellar** [comment]
I did not overlay the map in GoogleMaps. It is a print screen from that website.

**Comment by vinhk** [comment]
thanks
