### ISSUE TITLE
How did you find the direction of the coverage to reduce the number of turns?

### ISSUE THREAD

**Issue by vinhk** [gustavoavellar/multi-uav-planning#6]
Hi @gustavoavellar , I am unable understand how you determine the direction of the sweeping in your code.  I am working with a rectangle search area. But unable to make it cover to reduce number of turns. If you could give some explanation, that would be tremendous.

**Comment by gustavoavellar** [comment]
The best sweep direction is one which yields longer lines and less turns outside coverage area. Therefore, you are searching for a sweep direction that is perpendicular to the smallest projection of your polygon.

![image](https://user-images.githubusercontent.com/4855862/47180091-0d327b00-d2f6-11e8-9af7-4c29e991f9ee.png)

In my code, I search for this direction by rotating the polygon and looking for the smallest distance between maximum and minimum x coordinate. You can find this in [findStrips.m](https://github.com/gustavoavellar/multi-uav-planning/blob/master/findStrips.m)
