### ISSUE TITLE
Error occurs when running coverage.m due to m is NaN

### ISSUE THREAD

**Issue by ryrobotics** [gustavoavellar/multi-uav-planning#7]
Hi Gustavo,
Thank you for your useful code. But when I try to run the code, I find there are some errors, and I don't know how to sovle it.
The error message is shown below.
```
* Starting YALMIP integer branch & bound.
* Lower solver   : fmincon-standard
* Upper solver   : rounder
* Max time       : 3600
* Max iterations : Inf
 Node       Upper       Gap(%)     Lower     Open   Elapsed time

Index in position 3 is invalid. Array indices must be positive integers or logical values.

Error in coverage (line 110)
        waypoints{i} = findWaypoints(X(:,:,i),V);
````
I checked what happened there, it caused by for i = 1:m, but m is NaN. m comes from this code
`[X,v,m] = lip3(V,uav,uavSpeed,uavSetupTime,uavFlightTime,h,O);
`
However, in lip3.m there is no code to assign a value to m. I am not sure if it is my wrong understanding or I miss some necessary info. If you have any ideas, please let me know! Thank you very much!

**Comment by ryrobotics** [comment]
I have solved this problem. Gurobi is not set up properly.

**Comment by chenga02** [comment]
Hi @ryrobotics , 
Could you please tell me how to solve this problem?

**Comment by ryrobotics** [comment]
> Hi @ryrobotics , Could you please tell me how to solve this problem?

Hi @chenga02, this issue was quite a long time ago. I cannot remember the details, but it may be caused by the Gurobi itself, e.g., it is not activated correctly because the lack of license may cause Gurobi to return NaN.

Perhaps you can try to run some demos for Gurobi to validate if it is well set up.
