### ISSUE TITLE
Unrecognized function or variable 'sdpvar'.

### ISSUE THREAD

**Issue by koo-ec** [gustavoavellar/multi-uav-planning#8]
Thanks for sharing your codes. However, when I try your code, I get the following error: 

```
Unrecognized function or variable 'sdpvar'.

Error in lip3 (line 17)
v = sdpvar(1,1);

Error in coverage (line 70)
[X,v,m] = lip3(V,uav,uavSpeed,uavSetupTime,uavFlightTime,h,O);
```

**Comment by gustavoavellar** [comment]
You've got to install Yalmip toolbox in your matlab path.
[sdpvar](https://yalmip.github.io/command/sdpvar) is used to define YALMIPs symbolic decision variables.
https://yalmip.github.io

**Comment by koo-ec** [comment]
Thanks for your prompt response. The issue has been solved.
